import { DirectoryVendor, SubProcessorVendor, CompanySettings } from "./types";

export const INITIAL_COMPANY: CompanySettings = {
  name: "Acme SaaS Inc.",
  slug: "acme-saas",
  website: "https://acme.example.com",
  privacyEmail: "privacy@acme.example.com",
  dpoName: "Sarah Jenkins (CISO)",
  lastAuditDate: "2026-06-15",
  autoSyncPublicPage: true,
  theme: "light",
  notificationEmail: "security-alerts@acme.example.com",
};

export const DIRECTORY_VENDORS: DirectoryVendor[] = [
  {
    slug: "openai",
    name: "OpenAI",
    category: "AI & Machine Learning",
    description: "Generative AI models and LLM API endpoints (GPT-4o, embeddings, Whisper).",
    website: "https://openai.com",
    logoText: "OpenAI",
    dpaUrl: "https://openai.com/policies/business-terms/",
    subprocessorUrl: "https://platform.openai.com/subprocessors",
    certifications: ["SOC 2 Type II", "GDPR Compliant", "HIPAA"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["User Prompts", "API Request Metadata", "Chat Transcripts"],
    riskLevel: "Medium",
    privacyContact: "privacy@openai.com",
  },
  {
    slug: "anthropic",
    name: "Anthropic",
    category: "AI & Machine Learning",
    description: "Claude LLM API platform for AI-powered assistant and content processing.",
    website: "https://anthropic.com",
    logoText: "Anthropic",
    dpaUrl: "https://www.anthropic.com/legal/commercial-terms",
    subprocessorUrl: "https://www.anthropic.com/legal/subprocessors",
    certifications: ["SOC 2 Type II", "GDPR Compliant", "HIPAA"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["User Prompts", "API Context Payloads"],
    riskLevel: "Medium",
    privacyContact: "privacy@anthropic.com",
  },
  {
    slug: "amazon-web-services",
    name: "Amazon Web Services (AWS)",
    category: "Cloud Infrastructure & Hosting",
    description: "Cloud computing, managed containers, object storage, and serverless compute.",
    website: "https://aws.amazon.com",
    logoText: "AWS",
    dpaUrl: "https://aws.amazon.com/compliance/gdpr-center/",
    subprocessorUrl: "https://aws.amazon.com/compliance/sub-processors/",
    certifications: ["SOC 2 Type II", "ISO 27001", "HIPAA", "PCI-DSS", "GDPR Compliant"],
    headquarters: "Seattle, WA, USA",
    commonDataProcessed: ["Application Database", "Customer Storage Objects", "Server Logs"],
    riskLevel: "Low",
    privacyContact: "aws-privacy@amazon.com",
  },
  {
    slug: "google-cloud-platform",
    name: "Google Cloud Platform (GCP)",
    category: "Cloud Infrastructure & Hosting",
    description: "Enterprise cloud hosting, BigQuery data warehousing, and Kubernetes engine.",
    website: "https://cloud.google.com",
    logoText: "GCP",
    dpaUrl: "https://cloud.google.com/terms/data-processing-addendum",
    subprocessorUrl: "https://cloud.google.com/terms/subprocessors",
    certifications: ["SOC 2 Type II", "ISO 27001", "HIPAA", "PCI-DSS", "GDPR Compliant"],
    headquarters: "Mountain View, CA, USA",
    commonDataProcessed: ["Analytics Data", "Database Snapshots", "Cloud Storage Objects"],
    riskLevel: "Low",
    privacyContact: "cloud-privacy@google.com",
  },
  {
    slug: "stripe",
    name: "Stripe",
    category: "Payment Processing",
    description: "Online payment infrastructure, recurring subscriptions, and billing automation.",
    website: "https://stripe.com",
    logoText: "Stripe",
    dpaUrl: "https://stripe.com/dpa",
    subprocessorUrl: "https://stripe.com/service-providers",
    certifications: ["SOC 2 Type II", "PCI-DSS", "GDPR Compliant"],
    headquarters: "San Francisco, CA & Dublin, Ireland",
    commonDataProcessed: ["Cardholder Information", "Customer Billing Address", "Transaction Amounts"],
    riskLevel: "Low",
    privacyContact: "privacy@stripe.com",
  },
  {
    slug: "vercel",
    name: "Vercel",
    category: "Cloud Infrastructure & Hosting",
    description: "Frontend cloud deployment, serverless edge compute, and Next.js hosting.",
    website: "https://vercel.com",
    logoText: "Vercel",
    dpaUrl: "https://vercel.com/legal/dpa",
    subprocessorUrl: "https://vercel.com/legal/subprocessors",
    certifications: ["SOC 2 Type II", "ISO 27001", "GDPR Compliant"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["Edge Request Logs", "Client IP Addresses", "Serverless Invocation Payloads"],
    riskLevel: "Low",
    privacyContact: "privacy@vercel.com",
  },
  {
    slug: "supabase",
    name: "Supabase",
    category: "Database & Storage",
    description: "Managed Postgres database, real-time subscriptions, auth, and vector storage.",
    website: "https://supabase.com",
    logoText: "Supabase",
    dpaUrl: "https://supabase.com/legal/dpa",
    subprocessorUrl: "https://supabase.com/legal/sub-processors",
    certifications: ["SOC 2 Type II", "GDPR Compliant", "HIPAA"],
    headquarters: "Singapore & Remote",
    commonDataProcessed: ["Relational Application Records", "User Authentication Hashes", "File Uploads"],
    riskLevel: "Low",
    privacyContact: "privacy@supabase.com",
  },
  {
    slug: "cloudflare",
    name: "Cloudflare",
    category: "Authentication & Security",
    description: "Global CDN, DDoS mitigation, DNS management, and Web Application Firewall.",
    website: "https://cloudflare.com",
    logoText: "Cloudflare",
    dpaUrl: "https://www.cloudflare.com/cloudflare-customer-dpa/",
    subprocessorUrl: "https://www.cloudflare.com/subprocessor-list/",
    certifications: ["SOC 2 Type II", "ISO 27001", "PCI-DSS", "GDPR Compliant"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["Web Traffic Metadata", "Client IP Addresses", "TLS Handshakes"],
    riskLevel: "Low",
    privacyContact: "privacyquestions@cloudflare.com",
  },
  {
    slug: "resend",
    name: "Resend",
    category: "Customer Support & Communication",
    description: "Transactional email API for developers and modern web applications.",
    website: "https://resend.com",
    logoText: "Resend",
    dpaUrl: "https://resend.com/legal/dpa",
    subprocessorUrl: "https://resend.com/legal/subprocessors",
    certifications: ["SOC 2 Type II", "GDPR Compliant"],
    headquarters: "Remote",
    commonDataProcessed: ["Recipient Email Addresses", "Email Subject Lines", "Email Body Content"],
    riskLevel: "Medium",
    privacyContact: "legal@resend.com",
  },
  {
    slug: "twilio",
    name: "Twilio",
    category: "Customer Support & Communication",
    description: "SMS, voice, two-factor authentication, and communication APIs.",
    website: "https://twilio.com",
    logoText: "Twilio",
    dpaUrl: "https://www.twilio.com/en-us/legal/data-protection-addendum",
    subprocessorUrl: "https://www.twilio.com/en-us/legal/sub-processors",
    certifications: ["SOC 2 Type II", "ISO 27001", "HIPAA", "PCI-DSS", "GDPR Compliant"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["Phone Numbers", "SMS Content", "Call Recording Audio"],
    riskLevel: "Medium",
    privacyContact: "privacy@twilio.com",
  },
  {
    slug: "posthog",
    name: "PostHog",
    category: "Analytics & Observability",
    description: "Product analytics, session replay, feature flags, and A/B testing platform.",
    website: "https://posthog.com",
    logoText: "PostHog",
    dpaUrl: "https://posthog.com/terms#data-processing-agreement",
    subprocessorUrl: "https://posthog.com/docs/privacy/subprocessors",
    certifications: ["SOC 2 Type II", "GDPR Compliant", "HIPAA"],
    headquarters: "San Francisco, CA & London, UK",
    commonDataProcessed: ["User Click Events", "Browser Metadata", "Session Screen Recordings"],
    riskLevel: "Medium",
    privacyContact: "privacy@posthog.com",
  },
  {
    slug: "github",
    name: "GitHub",
    category: "Developer Tools & CI/CD",
    description: "Source code repository hosting, CI/CD Actions, and developer workflow automation.",
    website: "https://github.com",
    logoText: "GitHub",
    dpaUrl: "https://docs.github.com/en/site-policy/privacy-policies/github-data-protection-addendum",
    subprocessorUrl: "https://docs.github.com/en/site-policy/privacy-policies/github-subprocessors",
    certifications: ["SOC 2 Type II", "ISO 27001", "GDPR Compliant"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["Source Code", "Developer Commit Email", "Build Artifacts"],
    riskLevel: "Low",
    privacyContact: "privacy@github.com",
  },
  {
    slug: "sentry",
    name: "Sentry",
    category: "Analytics & Observability",
    description: "Application error tracking, performance monitoring, and crash reporting.",
    website: "https://sentry.io",
    logoText: "Sentry",
    dpaUrl: "https://sentry.io/legal/dpa/",
    subprocessorUrl: "https://sentry.io/legal/subprocessors/",
    certifications: ["SOC 2 Type II", "HIPAA", "GDPR Compliant"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["Stack Traces", "Client Error Breadcrumbs", "Browser Device Info"],
    riskLevel: "Low",
    privacyContact: "compliance@sentry.io",
  },
  {
    slug: "datadog",
    name: "Datadog",
    category: "Analytics & Observability",
    description: "Cloud-scale monitoring, log aggregation, APM, and infrastructure security.",
    website: "https://datadoghq.com",
    logoText: "Datadog",
    dpaUrl: "https://www.datadoghq.com/legal/data-processing-addendum/",
    subprocessorUrl: "https://www.datadoghq.com/legal/subprocessors/",
    certifications: ["SOC 2 Type II", "ISO 27001", "HIPAA", "PCI-DSS", "GDPR Compliant"],
    headquarters: "New York, NY, USA",
    commonDataProcessed: ["Server Performance Metrics", "System Logs", "APM Traces"],
    riskLevel: "Low",
    privacyContact: "privacy@datadoghq.com",
  },
  {
    slug: "clerk",
    name: "Clerk",
    category: "Authentication & Security",
    description: "User authentication, multi-tenant session management, and user profiles for Next.js and React.",
    website: "https://clerk.com",
    logoText: "Clerk",
    dpaUrl: "https://clerk.com/legal/dpa",
    subprocessorUrl: "https://clerk.com/legal/subprocessors",
    certifications: ["SOC 2 Type II", "GDPR Compliant", "HIPAA"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["User Email", "Password Hashes", "OAuth Tokens", "IP Address"],
    riskLevel: "Medium",
    privacyContact: "security@clerk.dev",
  },
  {
    slug: "pinecone",
    name: "Pinecone",
    category: "Database & Storage",
    description: "Vector database for semantic search, AI memory, and RAG knowledge retrieval.",
    website: "https://pinecone.io",
    logoText: "Pinecone",
    dpaUrl: "https://www.pinecone.io/legal/dpa/",
    subprocessorUrl: "https://www.pinecone.io/legal/subprocessors/",
    certifications: ["SOC 2 Type II", "GDPR Compliant", "HIPAA"],
    headquarters: "New York, NY, USA",
    commonDataProcessed: ["Document Vector Embeddings", "Metadata Key-Values"],
    riskLevel: "Medium",
    privacyContact: "privacy@pinecone.io",
  },
  {
    slug: "algolia",
    name: "Algolia",
    category: "Database & Storage",
    description: "Hosted search and discovery API engine for high-speed indexing.",
    website: "https://algolia.com",
    logoText: "Algolia",
    dpaUrl: "https://www.algolia.com/policies/dpa/",
    subprocessorUrl: "https://www.algolia.com/policies/subprocessors/",
    certifications: ["SOC 2 Type II", "ISO 27001", "GDPR Compliant", "HIPAA"],
    headquarters: "San Francisco, CA & Paris, France",
    commonDataProcessed: ["Search Queries", "Product Index Catalog", "User Search History"],
    riskLevel: "Low",
    privacyContact: "privacy@algolia.com",
  },
  {
    slug: "intercom",
    name: "Intercom",
    category: "Customer Support & Communication",
    description: "Customer service AI bot, live chat widget, and product tour messenger.",
    website: "https://intercom.com",
    logoText: "Intercom",
    dpaUrl: "https://www.intercom.com/legal/data-processing-agreement",
    subprocessorUrl: "https://www.intercom.com/legal/sub-processors",
    certifications: ["SOC 2 Type II", "GDPR Compliant", "HIPAA"],
    headquarters: "San Francisco, CA & Dublin, Ireland",
    commonDataProcessed: ["Customer Support Messages", "User Email", "Browser Information"],
    riskLevel: "Medium",
    privacyContact: "privacy@intercom.io",
  },
  {
    slug: "mixpanel",
    name: "Mixpanel",
    category: "Analytics & Observability",
    description: "Self-serve product analytics tracking conversion funnels and user retention.",
    website: "https://mixpanel.com",
    logoText: "Mixpanel",
    dpaUrl: "https://mixpanel.com/legal/dpa/",
    subprocessorUrl: "https://mixpanel.com/legal/subprocessors/",
    certifications: ["SOC 2 Type II", "ISO 27001", "GDPR Compliant", "HIPAA"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["User Action Events", "User Identifiers", "Custom User Properties"],
    riskLevel: "Medium",
    privacyContact: "privacy@mixpanel.com",
  },
  {
    slug: "upstash",
    name: "Upstash",
    category: "Database & Storage",
    description: "Serverless Redis, Kafka, and Vector database with per-request pricing.",
    website: "https://upstash.com",
    logoText: "Upstash",
    dpaUrl: "https://upstash.com/trust/dpa.pdf",
    subprocessorUrl: "https://upstash.com/trust/subprocessors",
    certifications: ["SOC 2 Type II", "GDPR Compliant"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["Cache Key-Values", "Rate Limiter Counters", "Queue Messages"],
    riskLevel: "Low",
    privacyContact: "privacy@upstash.com",
  },
  {
    slug: "mongodb-atlas",
    name: "MongoDB Atlas",
    category: "Database & Storage",
    description: "Fully-managed multi-cloud document database with global data distribution.",
    website: "https://mongodb.com",
    logoText: "MongoDB",
    dpaUrl: "https://www.mongodb.com/legal/dpa",
    subprocessorUrl: "https://www.mongodb.com/legal/subprocessors",
    certifications: ["SOC 2 Type II", "ISO 27001", "HIPAA", "PCI-DSS", "GDPR Compliant"],
    headquarters: "New York, NY, USA",
    commonDataProcessed: ["User Profile Documents", "Transactional Records", "Session Data"],
    riskLevel: "Low",
    privacyContact: "privacy@mongodb.com",
  },
  {
    slug: "linear",
    name: "Linear",
    category: "Developer Tools & CI/CD",
    description: "Issue tracking, project roadmap management, and engineering sprint coordination.",
    website: "https://linear.app",
    logoText: "Linear",
    dpaUrl: "https://linear.app/dpa",
    subprocessorUrl: "https://linear.app/security/subprocessors",
    certifications: ["SOC 2 Type II", "GDPR Compliant"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["Bug Reports", "Product Roadmaps", "Employee Email Addresses"],
    riskLevel: "Low",
    privacyContact: "privacy@linear.app",
  },
  {
    slug: "cohere",
    name: "Cohere",
    category: "AI & Machine Learning",
    description: "Enterprise foundation LLMs, semantic search, embeddings, and RAG retrieval APIs.",
    website: "https://cohere.com",
    logoText: "Cohere",
    dpaUrl: "https://cohere.com/legal/dpa",
    subprocessorUrl: "https://cohere.com/legal/subprocessors",
    certifications: ["SOC 2 Type II", "ISO 27001", "GDPR Compliant", "HIPAA"],
    headquarters: "Toronto, Canada & San Francisco, CA",
    commonDataProcessed: ["User Text Inputs", "Search Query Embeddings", "Document Context"],
    riskLevel: "Medium",
    privacyContact: "privacy@cohere.com",
  },
  {
    slug: "mistral-ai",
    name: "Mistral AI",
    category: "AI & Machine Learning",
    description: "Open and commercial frontier LLM inference APIs (Mistral Large, Codestral, Embeddings).",
    website: "https://mistral.ai",
    logoText: "Mistral",
    dpaUrl: "https://mistral.ai/terms/",
    subprocessorUrl: "https://mistral.ai/terms/#subprocessors",
    certifications: ["SOC 2 Type II", "GDPR Compliant", "ISO 27001"],
    headquarters: "Paris, France",
    commonDataProcessed: ["User Prompts", "Model Inference Outputs", "API Metadata"],
    riskLevel: "Medium",
    privacyContact: "privacy@mistral.ai",
  },
  {
    slug: "together-ai",
    name: "Together AI",
    category: "AI & Machine Learning",
    description: "Ultra-fast open-source generative AI model inference and dedicated GPU clusters.",
    website: "https://together.ai",
    logoText: "Together",
    dpaUrl: "https://www.together.ai/privacy",
    subprocessorUrl: "https://www.together.ai/subprocessors",
    certifications: ["SOC 2 Type II", "GDPR Compliant", "HIPAA"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["Model Input Tokens", "Inference Latency Logs", "API Payloads"],
    riskLevel: "Medium",
    privacyContact: "privacy@together.ai",
  },
  {
    slug: "replicate",
    name: "Replicate",
    category: "AI & Machine Learning",
    description: "Cloud API platform for running open-source machine learning models with a single line of code.",
    website: "https://replicate.com",
    logoText: "Replicate",
    dpaUrl: "https://replicate.com/privacy",
    subprocessorUrl: "https://replicate.com/subprocessors",
    certifications: ["SOC 2 Type II", "GDPR Compliant"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["Input Media Payloads", "Generated Images & Audio", "Prediction Metrics"],
    riskLevel: "Medium",
    privacyContact: "privacy@replicate.com",
  },
  {
    slug: "elevenlabs",
    name: "ElevenLabs",
    category: "AI & Machine Learning",
    description: "AI voice generation, lifelike speech synthesis, and real-time conversational audio API.",
    website: "https://elevenlabs.io",
    logoText: "ElevenLabs",
    dpaUrl: "https://elevenlabs.io/dpa",
    subprocessorUrl: "https://elevenlabs.io/subprocessors",
    certifications: ["SOC 2 Type II", "GDPR Compliant"],
    headquarters: "New York, NY & London, UK",
    commonDataProcessed: ["Text for Speech Synthesis", "Voice Audio Streams", "Account Metadata"],
    riskLevel: "Medium",
    privacyContact: "privacy@elevenlabs.io",
  },
  {
    slug: "deepgram",
    name: "Deepgram",
    category: "AI & Machine Learning",
    description: "Automated speech recognition (ASR) and text-to-speech AI APIs for live audio transcription.",
    website: "https://deepgram.com",
    logoText: "Deepgram",
    dpaUrl: "https://deepgram.com/dpa",
    subprocessorUrl: "https://deepgram.com/subprocessors",
    certifications: ["SOC 2 Type II", "HIPAA", "GDPR Compliant"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["Raw Audio Streams", "Transcription Texts", "Speaker Diarization Data"],
    riskLevel: "Medium",
    privacyContact: "privacy@deepgram.com",
  },
  {
    slug: "neon",
    name: "Neon",
    category: "Database & Storage",
    description: "Serverless Postgres database with separation of storage and compute, instant branching, and autoscaling.",
    website: "https://neon.tech",
    logoText: "Neon",
    dpaUrl: "https://neon.tech/dpa",
    subprocessorUrl: "https://neon.tech/subprocessors",
    certifications: ["SOC 2 Type II", "GDPR Compliant", "ISO 27001"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["Relational Database Tables", "SQL Query Payloads", "Database WAL Logs"],
    riskLevel: "Low",
    privacyContact: "privacy@neon.tech",
  },
  {
    slug: "planetscale",
    name: "PlanetScale",
    category: "Database & Storage",
    description: "Serverless MySQL platform powered by Vitess with zero-downtime schema migrations.",
    website: "https://planetscale.com",
    logoText: "PlanetScale",
    dpaUrl: "https://planetscale.com/legal/dpa",
    subprocessorUrl: "https://planetscale.com/legal/subprocessors",
    certifications: ["SOC 2 Type II", "GDPR Compliant", "HIPAA"],
    headquarters: "Mountain View, CA, USA",
    commonDataProcessed: ["MySQL Database Records", "Query Logs", "Schema Definitions"],
    riskLevel: "Low",
    privacyContact: "privacy@planetscale.com",
  },
  {
    slug: "auth0",
    name: "Auth0 by Okta",
    category: "Authentication & Security",
    description: "Enterprise identity management, Universal Login, multi-factor authentication (MFA), and SSO.",
    website: "https://auth0.com",
    logoText: "Auth0",
    dpaUrl: "https://www.okta.com/legal/dpa/",
    subprocessorUrl: "https://www.okta.com/trust-and-compliance/subprocessors/",
    certifications: ["SOC 2 Type II", "ISO 27001", "HIPAA", "PCI-DSS", "GDPR Compliant"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["User Email Addresses", "Password Hashes", "SAML SSO Assertions", "MFA Tokens"],
    riskLevel: "Low",
    privacyContact: "privacy@okta.com",
  },
  {
    slug: "workos",
    name: "WorkOS",
    category: "Authentication & Security",
    description: "Developer platform for Enterprise Single Sign-On (SSO), Directory Sync (SCIM), and Audit Logs.",
    website: "https://workos.com",
    logoText: "WorkOS",
    dpaUrl: "https://workos.com/legal/dpa",
    subprocessorUrl: "https://workos.com/legal/subprocessors",
    certifications: ["SOC 2 Type II", "GDPR Compliant", "HIPAA"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["Corporate User Directories", "SAML Metadata", "Enterprise Audit Events"],
    riskLevel: "Low",
    privacyContact: "security@workos.com",
  },
  {
    slug: "notion",
    name: "Notion",
    category: "Developer Tools & CI/CD",
    description: "Connected workspace for notes, documentation, project tracking, and internal knowledge bases.",
    website: "https://notion.so",
    logoText: "Notion",
    dpaUrl: "https://www.notion.so/help/data-processing-addendum",
    subprocessorUrl: "https://www.notion.so/help/subprocessors",
    certifications: ["SOC 2 Type II", "ISO 27001", "GDPR Compliant", "HIPAA"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["Internal Documentation", "Project Task Data", "Team Member Emails"],
    riskLevel: "Low",
    privacyContact: "privacy@makenotion.com",
  },
  {
    slug: "retool",
    name: "Retool",
    category: "Developer Tools & CI/CD",
    description: "Fast internal business software development platform connecting directly to databases and APIs.",
    website: "https://retool.com",
    logoText: "Retool",
    dpaUrl: "https://retool.com/legal/dpa",
    subprocessorUrl: "https://retool.com/legal/subprocessors",
    certifications: ["SOC 2 Type II", "GDPR Compliant", "HIPAA"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["Internal Query Configurations", "Employee Session Metadata"],
    riskLevel: "Low",
    privacyContact: "privacy@retool.com",
  },
  {
    slug: "sendgrid",
    name: "SendGrid by Twilio",
    category: "Customer Support & Communication",
    description: "Cloud-based email infrastructure platform delivering transactional messages at scale.",
    website: "https://sendgrid.com",
    logoText: "SendGrid",
    dpaUrl: "https://www.twilio.com/en-us/legal/data-protection-addendum",
    subprocessorUrl: "https://www.twilio.com/en-us/legal/sub-processors",
    certifications: ["SOC 2 Type II", "ISO 27001", "GDPR Compliant"],
    headquarters: "Denver, CO & San Francisco, CA",
    commonDataProcessed: ["Email Recipients", "Email Open/Click Metrics", "Outbound Email HTML"],
    riskLevel: "Medium",
    privacyContact: "privacy@sendgrid.com",
  },
  {
    slug: "segment",
    name: "Segment by Twilio",
    category: "Analytics & Observability",
    description: "Customer Data Platform (CDP) collecting, cleaning, and routing event telemetry across tools.",
    website: "https://segment.com",
    logoText: "Segment",
    dpaUrl: "https://segment.com/legal/data-processing-addendum/",
    subprocessorUrl: "https://segment.com/legal/subprocessors/",
    certifications: ["SOC 2 Type II", "ISO 27001", "HIPAA", "GDPR Compliant"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["User Event Telemetry", "User Identity Traits", "Device Identifiers"],
    riskLevel: "Medium",
    privacyContact: "privacy@segment.com",
  },
  {
    slug: "launchdarkly",
    name: "LaunchDarkly",
    category: "Developer Tools & CI/CD",
    description: "Enterprise feature management, canary rollouts, and targeted experimentation platform.",
    website: "https://launchdarkly.com",
    logoText: "LaunchDarkly",
    dpaUrl: "https://launchdarkly.com/policies/dpa/",
    subprocessorUrl: "https://launchdarkly.com/policies/subprocessors/",
    certifications: ["SOC 2 Type II", "ISO 27001", "GDPR Compliant", "HIPAA"],
    headquarters: "Oakland, CA, USA",
    commonDataProcessed: ["Feature Flag Evaluation Context", "User Targeting Keys", "Device Attributes"],
    riskLevel: "Low",
    privacyContact: "privacy@launchdarkly.com",
  },
  {
    slug: "pagerduty",
    name: "PagerDuty",
    category: "Analytics & Observability",
    description: "Digital operations management, real-time alerting, on-call schedules, and incident response.",
    website: "https://pagerduty.com",
    logoText: "PagerDuty",
    dpaUrl: "https://www.pagerduty.com/dpa/",
    subprocessorUrl: "https://www.pagerduty.com/subprocessors/",
    certifications: ["SOC 2 Type II", "ISO 27001", "HIPAA", "GDPR Compliant"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["System Incident Alerts", "On-Call Responder Phone Numbers", "Error Summaries"],
    riskLevel: "Low",
    privacyContact: "privacy@pagerduty.com",
  },
  {
    slug: "grafana-cloud",
    name: "Grafana Labs",
    category: "Analytics & Observability",
    description: "Operational dashboards, Prometheus metrics, Loki log aggregation, and Tempo tracing.",
    website: "https://grafana.com",
    logoText: "Grafana",
    dpaUrl: "https://grafana.com/legal/dpa/",
    subprocessorUrl: "https://grafana.com/legal/subprocessors/",
    certifications: ["SOC 2 Type II", "ISO 27001", "GDPR Compliant", "HIPAA"],
    headquarters: "New York, NY, USA",
    commonDataProcessed: ["Server Telemetry Metrics", "Application Trace Spans", "Log Streams"],
    riskLevel: "Low",
    privacyContact: "privacy@grafana.com",
  },
  {
    slug: "render",
    name: "Render",
    category: "Cloud Infrastructure & Hosting",
    description: "Unified cloud hosting for web applications, background workers, and managed PostgreSQL databases.",
    website: "https://render.com",
    logoText: "Render",
    dpaUrl: "https://render.com/privacy",
    subprocessorUrl: "https://render.com/subprocessors",
    certifications: ["SOC 2 Type II", "GDPR Compliant"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["Application Deployments", "Container Logs", "Environment Secrets"],
    riskLevel: "Low",
    privacyContact: "privacy@render.com",
  },
  {
    slug: "fly-io",
    name: "Fly.io",
    category: "Cloud Infrastructure & Hosting",
    description: "Global edge compute platform running full-stack Docker containers physically close to users.",
    website: "https://fly.io",
    logoText: "Fly.io",
    dpaUrl: "https://fly.io/docs/about/dpa/",
    subprocessorUrl: "https://fly.io/docs/about/subprocessors/",
    certifications: ["SOC 2 Type II", "GDPR Compliant"],
    headquarters: "Chicago, IL, USA",
    commonDataProcessed: ["Application Containers", "Edge Network Traffic", "Volume Storage"],
    riskLevel: "Low",
    privacyContact: "privacy@fly.io",
  },
  {
    slug: "railway",
    name: "Railway",
    category: "Cloud Infrastructure & Hosting",
    description: "Instant cloud infrastructure deployment platform for databases, microservices, and web servers.",
    website: "https://railway.app",
    logoText: "Railway",
    dpaUrl: "https://railway.app/legal/dpa",
    subprocessorUrl: "https://railway.app/legal/subprocessors",
    certifications: ["SOC 2 Type II", "GDPR Compliant"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["Service Logs", "Application Data", "Configuration Variables"],
    riskLevel: "Low",
    privacyContact: "privacy@railway.app",
  },
  {
    slug: "digitalocean",
    name: "DigitalOcean",
    category: "Cloud Infrastructure & Hosting",
    description: "Cloud droplets, Managed Kubernetes, managed databases, and Spaces object storage.",
    website: "https://digitalocean.com",
    logoText: "DigitalOcean",
    dpaUrl: "https://www.digitalocean.com/legal/data-processing-agreement",
    subprocessorUrl: "https://www.digitalocean.com/legal/sub-processors",
    certifications: ["SOC 2 Type II", "ISO 27001", "PCI-DSS", "GDPR Compliant"],
    headquarters: "New York, NY, USA",
    commonDataProcessed: ["Virtual Server Disks", "Object Storage Assets", "Network IP Routing"],
    riskLevel: "Low",
    privacyContact: "privacy@digitalocean.com",
  },
  {
    slug: "snowflake",
    name: "Snowflake",
    category: "Database & Storage",
    description: "Cloud data warehouse, AI data cloud, and enterprise data analytics platform.",
    website: "https://snowflake.com",
    logoText: "Snowflake",
    dpaUrl: "https://www.snowflake.com/legal/data-processing-addendum/",
    subprocessorUrl: "https://www.snowflake.com/legal/subprocessors/",
    certifications: ["SOC 2 Type II", "ISO 27001", "HIPAA", "PCI-DSS", "GDPR Compliant"],
    headquarters: "Bozeman, MT, USA",
    commonDataProcessed: ["Analytical Datasets", "Business Intelligence Queries", "ETL Pipelines"],
    riskLevel: "Low",
    privacyContact: "privacy@snowflake.com",
  },
  {
    slug: "databricks",
    name: "Databricks",
    category: "Database & Storage",
    description: "Unified analytics, Apache Spark lakehouse, and enterprise machine learning infrastructure.",
    website: "https://databricks.com",
    logoText: "Databricks",
    dpaUrl: "https://www.databricks.com/legal/dpa",
    subprocessorUrl: "https://www.databricks.com/legal/subprocessors",
    certifications: ["SOC 2 Type II", "ISO 27001", "HIPAA", "PCI-DSS", "GDPR Compliant"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["Lakehouse Tables", "Machine Learning Training Data", "Spark Job Logs"],
    riskLevel: "Low",
    privacyContact: "privacy@databricks.com",
  },
  {
    slug: "elastic",
    name: "Elastic (Elasticsearch)",
    category: "Database & Storage",
    description: "Elasticsearch, Kibana, and vector database search and security analysis cloud.",
    website: "https://elastic.co",
    logoText: "Elastic",
    dpaUrl: "https://www.elastic.co/legal/data-processing-addendum",
    subprocessorUrl: "https://www.elastic.co/legal/subprocessors",
    certifications: ["SOC 2 Type II", "ISO 27001", "HIPAA", "GDPR Compliant"],
    headquarters: "San Francisco, CA & Amsterdam, Netherlands",
    commonDataProcessed: ["Full-Text Search Indices", "Security Audit Logs", "System Observability Traces"],
    riskLevel: "Low",
    privacyContact: "privacy@elastic.co",
  },
  {
    slug: "pusher",
    name: "Pusher by MessageBird",
    category: "Developer Tools & CI/CD",
    description: "Real-time bidirectional WebSocket APIs, notifications, and in-app chat infrastructure.",
    website: "https://pusher.com",
    logoText: "Pusher",
    dpaUrl: "https://pusher.com/legal/dpa",
    subprocessorUrl: "https://pusher.com/legal/subprocessors",
    certifications: ["SOC 2 Type II", "GDPR Compliant", "HIPAA"],
    headquarters: "London, UK & Amsterdam, Netherlands",
    commonDataProcessed: ["WebSocket Message Payloads", "Socket Connection IDs", "Channel Names"],
    riskLevel: "Medium",
    privacyContact: "privacy@pusher.com",
  },
  {
    slug: "mux",
    name: "Mux",
    category: "Developer Tools & CI/CD",
    description: "Real-time video streaming, on-demand video encoding, and video performance analytics API.",
    website: "https://mux.com",
    logoText: "Mux",
    dpaUrl: "https://mux.com/legal/dpa",
    subprocessorUrl: "https://mux.com/legal/subprocessors",
    certifications: ["SOC 2 Type II", "GDPR Compliant", "HIPAA"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["Video Upload Streams", "Viewer Playback Metrics", "HLS Segment Files"],
    riskLevel: "Medium",
    privacyContact: "privacy@mux.com",
  },
  {
    slug: "plaid",
    name: "Plaid",
    category: "Payment Processing",
    description: "Secure financial API connecting consumer bank accounts to fintech applications.",
    website: "https://plaid.com",
    logoText: "Plaid",
    dpaUrl: "https://plaid.com/legal/dpa/",
    subprocessorUrl: "https://plaid.com/legal/subprocessors/",
    certifications: ["SOC 2 Type II", "ISO 27001", "PCI-DSS", "GDPR Compliant"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["Bank Account Numbers", "ACH Routing Codes", "Financial Transaction History"],
    riskLevel: "High",
    privacyContact: "privacy@plaid.com",
  },
  {
    slug: "hubspot",
    name: "HubSpot",
    category: "Customer Support & Communication",
    description: "Inbound CRM, sales pipeline tracking, marketing automation, and customer helpdesk.",
    website: "https://hubspot.com",
    logoText: "HubSpot",
    dpaUrl: "https://legal.hubspot.com/dpa",
    subprocessorUrl: "https://legal.hubspot.com/sub-processors-page",
    certifications: ["SOC 2 Type II", "ISO 27001", "GDPR Compliant", "HIPAA"],
    headquarters: "Cambridge, MA, USA",
    commonDataProcessed: ["Sales Lead Names", "Customer Contact Emails", "Marketing Interaction History"],
    riskLevel: "Medium",
    privacyContact: "privacy@hubspot.com",
  },
];

export const INITIAL_REGISTER_VENDORS: SubProcessorVendor[] = [
  {
    id: "v-1",
    name: "OpenAI",
    slug: "openai",
    description: "Generative AI completions and embedding endpoints for customer assistant.",
    category: "AI & Machine Learning",
    website: "https://openai.com",
    dataProcessed: ["User Prompts", "Support Ticket Text"],
    dataLocation: "United States (US-East)",
    dpaUrl: "https://openai.com/policies/business-terms/",
    dpaStatus: "Signed",
    certifications: ["SOC 2 Type II", "GDPR Compliant", "HIPAA"],
    riskLevel: "Medium",
    lastReviewedDate: "2026-05-10",
    nextReviewDate: "2027-05-10",
    notes: "Zero data retention agreement active on API tier.",
    isPublic: true,
    addedAt: "2026-01-15T10:00:00Z",
  },
  {
    id: "v-2",
    name: "Amazon Web Services (AWS)",
    slug: "amazon-web-services",
    description: "Core cloud infrastructure, RDS PostgreSQL, S3 asset storage, and ECS.",
    category: "Cloud Infrastructure & Hosting",
    website: "https://aws.amazon.com",
    dataProcessed: ["All Customer Application Data", "Database Records", "Uploaded Assets"],
    dataLocation: "United States (US-East-1)",
    dpaUrl: "https://aws.amazon.com/compliance/gdpr-center/",
    dpaStatus: "Signed",
    certifications: ["SOC 2 Type II", "ISO 27001", "HIPAA", "PCI-DSS", "GDPR Compliant"],
    riskLevel: "Low",
    lastReviewedDate: "2026-06-01",
    nextReviewDate: "2027-06-01",
    notes: "Enterprise DPA attached to AWS Org root account.",
    isPublic: true,
    addedAt: "2026-01-10T08:00:00Z",
  },
  {
    id: "v-3",
    name: "Stripe",
    slug: "stripe",
    description: "Payment gateway, customer billing records, and invoice receipts.",
    category: "Payment Processing",
    website: "https://stripe.com",
    dataProcessed: ["Billing Email", "Payment Method Tokens", "Transaction Totals"],
    dataLocation: "United States & European Union",
    dpaUrl: "https://stripe.com/dpa",
    dpaStatus: "Signed",
    certifications: ["SOC 2 Type II", "PCI-DSS", "GDPR Compliant"],
    riskLevel: "Low",
    lastReviewedDate: "2026-04-12",
    nextReviewDate: "2027-04-12",
    notes: "PCI DSS Level 1 compliant processor.",
    isPublic: true,
    addedAt: "2026-01-10T08:30:00Z",
  },
  {
    id: "v-4",
    name: "Vercel",
    slug: "vercel",
    description: "Next.js frontend hosting, Edge Middleware, and DNS routing.",
    category: "Cloud Infrastructure & Hosting",
    website: "https://vercel.com",
    dataProcessed: ["Client Request IPs", "Transient HTTP Headers"],
    dataLocation: "Global Edge Network",
    dpaUrl: "https://vercel.com/legal/dpa",
    dpaStatus: "Signed",
    certifications: ["SOC 2 Type II", "ISO 27001", "GDPR Compliant"],
    riskLevel: "Low",
    lastReviewedDate: "2026-06-10",
    nextReviewDate: "2027-06-10",
    notes: "Signed Enterprise Terms & DPA on file.",
    isPublic: true,
    addedAt: "2026-01-11T09:15:00Z",
  },
  {
    id: "v-5",
    name: "Resend",
    slug: "resend",
    description: "Transactional notifications, welcome emails, and password resets.",
    category: "Customer Support & Communication",
    website: "https://resend.com",
    dataProcessed: ["Recipient Email", "Notification Body Content"],
    dataLocation: "United States (US-East)",
    dpaUrl: "https://resend.com/legal/dpa",
    dpaStatus: "Under Review",
    certifications: ["SOC 2 Type II", "GDPR Compliant"],
    riskLevel: "Medium",
    lastReviewedDate: "2026-07-01",
    nextReviewDate: "2026-09-01",
    notes: "Annual vendor reassessment due before upcoming audit.",
    isPublic: true,
    addedAt: "2026-02-01T11:00:00Z",
  },
  {
    id: "v-6",
    name: "PostHog",
    slug: "posthog",
    description: "Product telemetry, feature flags, and anonymous conversion funnels.",
    category: "Analytics & Observability",
    website: "https://posthog.com",
    dataProcessed: ["User Action Events", "Browser Device Type", "Pseudonymous IDs"],
    dataLocation: "United States (US-East)",
    dpaUrl: "https://posthog.com/terms#data-processing-agreement",
    dpaStatus: "Signed",
    certifications: ["SOC 2 Type II", "GDPR Compliant"],
    riskLevel: "Low",
    lastReviewedDate: "2026-05-20",
    nextReviewDate: "2027-05-20",
    notes: "EU/US DPA signed. IP masking enabled by default.",
    isPublic: true,
    addedAt: "2026-02-10T14:30:00Z",
  },
  {
    id: "v-7",
    name: "Sentry",
    slug: "sentry",
    description: "Real-time error monitoring and exception tracking.",
    category: "Analytics & Observability",
    website: "https://sentry.io",
    dataProcessed: ["Client Stack Traces", "Browser Metadata"],
    dataLocation: "United States",
    dpaUrl: "https://sentry.io/legal/dpa/",
    dpaStatus: "Signed",
    certifications: ["SOC 2 Type II", "HIPAA", "GDPR Compliant"],
    riskLevel: "Low",
    lastReviewedDate: "2026-03-15",
    nextReviewDate: "2027-03-15",
    notes: "Data scrubbing configured to remove PII from error payloads.",
    isPublic: true,
    addedAt: "2026-02-15T16:00:00Z",
  },
  {
    id: "v-8",
    name: "Pinecone",
    slug: "pinecone",
    description: "Managed vector database storing semantic document embeddings.",
    category: "Database & Storage",
    website: "https://pinecone.io",
    dataProcessed: ["Document Vector Embeddings", "Document IDs"],
    dataLocation: "United States (US-East-1)",
    dpaUrl: "https://www.pinecone.io/legal/dpa/",
    dpaStatus: "Missing",
    certifications: ["SOC 2 Type II", "GDPR Compliant"],
    riskLevel: "High",
    lastReviewedDate: "2026-01-20",
    nextReviewDate: "2026-08-30",
    notes: "Action item: Execute formal DPA with Pinecone legal team.",
    isPublic: false,
    addedAt: "2026-03-01T10:00:00Z",
  }
];
