import { DirectoryVendor, SubProcessorVendor, CompanySettings } from "./types";

export const INITIAL_COMPANY: CompanySettings = {
  name: "Acme SaaS Inc.",
  slug: "acme-saas",
  website: "https://acme.example.com",
  privacyEmail: "privacy@acme.example.com",
  dpoName: "Sarah Jenkins (CISO)",
  lastAuditDate: "2026-06-15",
  autoSyncPublicPage: true,
  theme: "light",
  notificationEmail: "security-alerts@acme.example.com",
};

export const DIRECTORY_VENDORS: DirectoryVendor[] = [
  {
    slug: "openai",
    name: "OpenAI",
    category: "AI & Machine Learning",
    description: "Generative AI models and LLM API endpoints (GPT-4o, embeddings, Whisper).",
    website: "https://openai.com",
    logoText: "OpenAI",
    dpaUrl: "https://openai.com/policies/business-terms/",
    subprocessorUrl: "https://platform.openai.com/subprocessors",
    certifications: ["SOC 2 Type II", "GDPR Compliant", "HIPAA"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["User Prompts", "API Request Metadata", "Chat Transcripts"],
    riskLevel: "Medium",
    privacyContact: "privacy@openai.com",
  },
  {
    slug: "anthropic",
    name: "Anthropic",
    category: "AI & Machine Learning",
    description: "Claude LLM API platform for AI-powered assistant and content processing.",
    website: "https://anthropic.com",
    logoText: "Anthropic",
    dpaUrl: "https://www.anthropic.com/legal/commercial-terms",
    subprocessorUrl: "https://www.anthropic.com/legal/subprocessors",
    certifications: ["SOC 2 Type II", "GDPR Compliant", "HIPAA"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["User Prompts", "API Context Payloads"],
    riskLevel: "Medium",
    privacyContact: "privacy@anthropic.com",
  },
  {
    slug: "amazon-web-services",
    name: "Amazon Web Services (AWS)",
    category: "Cloud Infrastructure & Hosting",
    description: "Cloud computing, managed containers, object storage, and serverless compute.",
    website: "https://aws.amazon.com",
    logoText: "AWS",
    dpaUrl: "https://aws.amazon.com/compliance/gdpr-center/",
    subprocessorUrl: "https://aws.amazon.com/compliance/sub-processors/",
    certifications: ["SOC 2 Type II", "ISO 27001", "HIPAA", "PCI-DSS", "GDPR Compliant"],
    headquarters: "Seattle, WA, USA",
    commonDataProcessed: ["Application Database", "Customer Storage Objects", "Server Logs"],
    riskLevel: "Low",
    privacyContact: "aws-privacy@amazon.com",
  },
  {
    slug: "google-cloud-platform",
    name: "Google Cloud Platform (GCP)",
    category: "Cloud Infrastructure & Hosting",
    description: "Enterprise cloud hosting, BigQuery data warehousing, and Kubernetes engine.",
    website: "https://cloud.google.com",
    logoText: "GCP",
    dpaUrl: "https://cloud.google.com/terms/data-processing-addendum",
    subprocessorUrl: "https://cloud.google.com/terms/subprocessors",
    certifications: ["SOC 2 Type II", "ISO 27001", "HIPAA", "PCI-DSS", "GDPR Compliant"],
    headquarters: "Mountain View, CA, USA",
    commonDataProcessed: ["Analytics Data", "Database Snapshots", "Cloud Storage Objects"],
    riskLevel: "Low",
    privacyContact: "cloud-privacy@google.com",
  },
  {
    slug: "stripe",
    name: "Stripe",
    category: "Payment Processing",
    description: "Online payment infrastructure, recurring subscriptions, and billing automation.",
    website: "https://stripe.com",
    logoText: "Stripe",
    dpaUrl: "https://stripe.com/dpa",
    subprocessorUrl: "https://stripe.com/service-providers",
    certifications: ["SOC 2 Type II", "PCI-DSS", "GDPR Compliant"],
    headquarters: "San Francisco, CA & Dublin, Ireland",
    commonDataProcessed: ["Cardholder Information", "Customer Billing Address", "Transaction Amounts"],
    riskLevel: "Low",
    privacyContact: "privacy@stripe.com",
  },
  {
    slug: "vercel",
    name: "Vercel",
    category: "Cloud Infrastructure & Hosting",
    description: "Frontend cloud deployment, serverless edge compute, and Next.js hosting.",
    website: "https://vercel.com",
    logoText: "Vercel",
    dpaUrl: "https://vercel.com/legal/dpa",
    subprocessorUrl: "https://vercel.com/legal/subprocessors",
    certifications: ["SOC 2 Type II", "ISO 27001", "GDPR Compliant"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["Edge Request Logs", "Client IP Addresses", "Serverless Invocation Payloads"],
    riskLevel: "Low",
    privacyContact: "privacy@vercel.com",
  },
  {
    slug: "supabase",
    name: "Supabase",
    category: "Database & Storage",
    description: "Managed Postgres database, real-time subscriptions, auth, and vector storage.",
    website: "https://supabase.com",
    logoText: "Supabase",
    dpaUrl: "https://supabase.com/legal/dpa",
    subprocessorUrl: "https://supabase.com/legal/sub-processors",
    certifications: ["SOC 2 Type II", "GDPR Compliant", "HIPAA"],
    headquarters: "Singapore & Remote",
    commonDataProcessed: ["Relational Application Records", "User Authentication Hashes", "File Uploads"],
    riskLevel: "Low",
    privacyContact: "privacy@supabase.com",
  },
  {
    slug: "cloudflare",
    name: "Cloudflare",
    category: "Authentication & Security",
    description: "Global CDN, DDoS mitigation, DNS management, and Web Application Firewall.",
    website: "https://cloudflare.com",
    logoText: "Cloudflare",
    dpaUrl: "https://www.cloudflare.com/cloudflare-customer-dpa/",
    subprocessorUrl: "https://www.cloudflare.com/subprocessor-list/",
    certifications: ["SOC 2 Type II", "ISO 27001", "PCI-DSS", "GDPR Compliant"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["Web Traffic Metadata", "Client IP Addresses", "TLS Handshakes"],
    riskLevel: "Low",
    privacyContact: "privacyquestions@cloudflare.com",
  },
  {
    slug: "resend",
    name: "Resend",
    category: "Customer Support & Communication",
    description: "Transactional email API for developers and modern web applications.",
    website: "https://resend.com",
    logoText: "Resend",
    dpaUrl: "https://resend.com/legal/dpa",
    subprocessorUrl: "https://resend.com/legal/subprocessors",
    certifications: ["SOC 2 Type II", "GDPR Compliant"],
    headquarters: "Remote",
    commonDataProcessed: ["Recipient Email Addresses", "Email Subject Lines", "Email Body Content"],
    riskLevel: "Medium",
    privacyContact: "legal@resend.com",
  },
  {
    slug: "twilio",
    name: "Twilio",
    category: "Customer Support & Communication",
    description: "SMS, voice, two-factor authentication, and communication APIs.",
    website: "https://twilio.com",
    logoText: "Twilio",
    dpaUrl: "https://www.twilio.com/en-us/legal/data-protection-addendum",
    subprocessorUrl: "https://www.twilio.com/en-us/legal/sub-processors",
    certifications: ["SOC 2 Type II", "ISO 27001", "HIPAA", "PCI-DSS", "GDPR Compliant"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["Phone Numbers", "SMS Content", "Call Recording Audio"],
    riskLevel: "Medium",
    privacyContact: "privacy@twilio.com",
  },
  {
    slug: "posthog",
    name: "PostHog",
    category: "Analytics & Observability",
    description: "Product analytics, session replay, feature flags, and A/B testing platform.",
    website: "https://posthog.com",
    logoText: "PostHog",
    dpaUrl: "https://posthog.com/terms#data-processing-agreement",
    subprocessorUrl: "https://posthog.com/docs/privacy/subprocessors",
    certifications: ["SOC 2 Type II", "GDPR Compliant", "HIPAA"],
    headquarters: "San Francisco, CA & London, UK",
    commonDataProcessed: ["User Click Events", "Browser Metadata", "Session Screen Recordings"],
    riskLevel: "Medium",
    privacyContact: "privacy@posthog.com",
  },
  {
    slug: "github",
    name: "GitHub",
    category: "Developer Tools & CI/CD",
    description: "Source code repository hosting, CI/CD Actions, and developer workflow automation.",
    website: "https://github.com",
    logoText: "GitHub",
    dpaUrl: "https://docs.github.com/en/site-policy/privacy-policies/github-data-protection-addendum",
    subprocessorUrl: "https://docs.github.com/en/site-policy/privacy-policies/github-subprocessors",
    certifications: ["SOC 2 Type II", "ISO 27001", "GDPR Compliant"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["Source Code", "Developer Commit Email", "Build Artifacts"],
    riskLevel: "Low",
    privacyContact: "privacy@github.com",
  },
  {
    slug: "sentry",
    name: "Sentry",
    category: "Analytics & Observability",
    description: "Application error tracking, performance monitoring, and crash reporting.",
    website: "https://sentry.io",
    logoText: "Sentry",
    dpaUrl: "https://sentry.io/legal/dpa/",
    subprocessorUrl: "https://sentry.io/legal/subprocessors/",
    certifications: ["SOC 2 Type II", "HIPAA", "GDPR Compliant"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["Stack Traces", "Client Error Breadcrumbs", "Browser Device Info"],
    riskLevel: "Low",
    privacyContact: "compliance@sentry.io",
  },
  {
    slug: "datadog",
    name: "Datadog",
    category: "Analytics & Observability",
    description: "Cloud-scale monitoring, log aggregation, APM, and infrastructure security.",
    website: "https://datadoghq.com",
    logoText: "Datadog",
    dpaUrl: "https://www.datadoghq.com/legal/data-processing-addendum/",
    subprocessorUrl: "https://www.datadoghq.com/legal/subprocessors/",
    certifications: ["SOC 2 Type II", "ISO 27001", "HIPAA", "PCI-DSS", "GDPR Compliant"],
    headquarters: "New York, NY, USA",
    commonDataProcessed: ["Server Performance Metrics", "System Logs", "APM Traces"],
    riskLevel: "Low",
    privacyContact: "privacy@datadoghq.com",
  },
  {
    slug: "clerk",
    name: "Clerk",
    category: "Authentication & Security",
    description: "User authentication, multi-tenant session management, and user profiles for Next.js and React.",
    website: "https://clerk.com",
    logoText: "Clerk",
    dpaUrl: "https://clerk.com/legal/dpa",
    subprocessorUrl: "https://clerk.com/legal/subprocessors",
    certifications: ["SOC 2 Type II", "GDPR Compliant", "HIPAA"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["User Email", "Password Hashes", "OAuth Tokens", "IP Address"],
    riskLevel: "Medium",
    privacyContact: "security@clerk.dev",
  },
  {
    slug: "pinecone",
    name: "Pinecone",
    category: "Database & Storage",
    description: "Vector database for semantic search, AI memory, and RAG knowledge retrieval.",
    website: "https://pinecone.io",
    logoText: "Pinecone",
    dpaUrl: "https://www.pinecone.io/legal/dpa/",
    subprocessorUrl: "https://www.pinecone.io/legal/subprocessors/",
    certifications: ["SOC 2 Type II", "GDPR Compliant", "HIPAA"],
    headquarters: "New York, NY, USA",
    commonDataProcessed: ["Document Vector Embeddings", "Metadata Key-Values"],
    riskLevel: "Medium",
    privacyContact: "privacy@pinecone.io",
  },
  {
    slug: "algolia",
    name: "Algolia",
    category: "Database & Storage",
    description: "Hosted search and discovery API engine for high-speed indexing.",
    website: "https://algolia.com",
    logoText: "Algolia",
    dpaUrl: "https://www.algolia.com/policies/dpa/",
    subprocessorUrl: "https://www.algolia.com/policies/subprocessors/",
    certifications: ["SOC 2 Type II", "ISO 27001", "GDPR Compliant", "HIPAA"],
    headquarters: "San Francisco, CA & Paris, France",
    commonDataProcessed: ["Search Queries", "Product Index Catalog", "User Search History"],
    riskLevel: "Low",
    privacyContact: "privacy@algolia.com",
  },
  {
    slug: "intercom",
    name: "Intercom",
    category: "Customer Support & Communication",
    description: "Customer service AI bot, live chat widget, and product tour messenger.",
    website: "https://intercom.com",
    logoText: "Intercom",
    dpaUrl: "https://www.intercom.com/legal/data-processing-agreement",
    subprocessorUrl: "https://www.intercom.com/legal/sub-processors",
    certifications: ["SOC 2 Type II", "GDPR Compliant", "HIPAA"],
    headquarters: "San Francisco, CA & Dublin, Ireland",
    commonDataProcessed: ["Customer Support Messages", "User Email", "Browser Information"],
    riskLevel: "Medium",
    privacyContact: "privacy@intercom.io",
  },
  {
    slug: "mixpanel",
    name: "Mixpanel",
    category: "Analytics & Observability",
    description: "Self-serve product analytics tracking conversion funnels and user retention.",
    website: "https://mixpanel.com",
    logoText: "Mixpanel",
    dpaUrl: "https://mixpanel.com/legal/dpa/",
    subprocessorUrl: "https://mixpanel.com/legal/subprocessors/",
    certifications: ["SOC 2 Type II", "ISO 27001", "GDPR Compliant", "HIPAA"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["User Action Events", "User Identifiers", "Custom User Properties"],
    riskLevel: "Medium",
    privacyContact: "privacy@mixpanel.com",
  },
  {
    slug: "upstash",
    name: "Upstash",
    category: "Database & Storage",
    description: "Serverless Redis, Kafka, and Vector database with per-request pricing.",
    website: "https://upstash.com",
    logoText: "Upstash",
    dpaUrl: "https://upstash.com/trust/dpa.pdf",
    subprocessorUrl: "https://upstash.com/trust/subprocessors",
    certifications: ["SOC 2 Type II", "GDPR Compliant"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["Cache Key-Values", "Rate Limiter Counters", "Queue Messages"],
    riskLevel: "Low",
    privacyContact: "privacy@upstash.com",
  },
  {
    slug: "mongodb-atlas",
    name: "MongoDB Atlas",
    category: "Database & Storage",
    description: "Fully-managed multi-cloud document database with global data distribution.",
    website: "https://mongodb.com",
    logoText: "MongoDB",
    dpaUrl: "https://www.mongodb.com/legal/dpa",
    subprocessorUrl: "https://www.mongodb.com/legal/subprocessors",
    certifications: ["SOC 2 Type II", "ISO 27001", "HIPAA", "PCI-DSS", "GDPR Compliant"],
    headquarters: "New York, NY, USA",
    commonDataProcessed: ["User Profile Documents", "Transactional Records", "Session Data"],
    riskLevel: "Low",
    privacyContact: "privacy@mongodb.com",
  },
  {
    slug: "linear",
    name: "Linear",
    category: "Developer Tools & CI/CD",
    description: "Issue tracking, project roadmap management, and engineering sprint coordination.",
    website: "https://linear.app",
    logoText: "Linear",
    dpaUrl: "https://linear.app/dpa",
    subprocessorUrl: "https://linear.app/security/subprocessors",
    certifications: ["SOC 2 Type II", "GDPR Compliant"],
    headquarters: "San Francisco, CA, USA",
    commonDataProcessed: ["Bug Reports", "Product Roadmaps", "Employee Email Addresses"],
    riskLevel: "Low",
    privacyContact: "privacy@linear.app",
  },
];

export const INITIAL_REGISTER_VENDORS: SubProcessorVendor[] = [
  {
    id: "v-1",
    name: "OpenAI",
    slug: "openai",
    description: "Generative AI completions and embedding endpoints for customer assistant.",
    category: "AI & Machine Learning",
    website: "https://openai.com",
    dataProcessed: ["User Prompts", "Support Ticket Text"],
    dataLocation: "United States (US-East)",
    dpaUrl: "https://openai.com/policies/business-terms/",
    dpaStatus: "Signed",
    certifications: ["SOC 2 Type II", "GDPR Compliant", "HIPAA"],
    riskLevel: "Medium",
    lastReviewedDate: "2026-05-10",
    nextReviewDate: "2027-05-10",
    notes: "Zero data retention agreement active on API tier.",
    isPublic: true,
    addedAt: "2026-01-15T10:00:00Z",
  },
  {
    id: "v-2",
    name: "Amazon Web Services (AWS)",
    slug: "amazon-web-services",
    description: "Core cloud infrastructure, RDS PostgreSQL, S3 asset storage, and ECS.",
    category: "Cloud Infrastructure & Hosting",
    website: "https://aws.amazon.com",
    dataProcessed: ["All Customer Application Data", "Database Records", "Uploaded Assets"],
    dataLocation: "United States (US-East-1)",
    dpaUrl: "https://aws.amazon.com/compliance/gdpr-center/",
    dpaStatus: "Signed",
    certifications: ["SOC 2 Type II", "ISO 27001", "HIPAA", "PCI-DSS", "GDPR Compliant"],
    riskLevel: "Low",
    lastReviewedDate: "2026-06-01",
    nextReviewDate: "2027-06-01",
    notes: "Enterprise DPA attached to AWS Org root account.",
    isPublic: true,
    addedAt: "2026-01-10T08:00:00Z",
  },
  {
    id: "v-3",
    name: "Stripe",
    slug: "stripe",
    description: "Payment gateway, customer billing records, and invoice receipts.",
    category: "Payment Processing",
    website: "https://stripe.com",
    dataProcessed: ["Billing Email", "Payment Method Tokens", "Transaction Totals"],
    dataLocation: "United States & European Union",
    dpaUrl: "https://stripe.com/dpa",
    dpaStatus: "Signed",
    certifications: ["SOC 2 Type II", "PCI-DSS", "GDPR Compliant"],
    riskLevel: "Low",
    lastReviewedDate: "2026-04-12",
    nextReviewDate: "2027-04-12",
    notes: "PCI DSS Level 1 compliant processor.",
    isPublic: true,
    addedAt: "2026-01-10T08:30:00Z",
  },
  {
    id: "v-4",
    name: "Vercel",
    slug: "vercel",
    description: "Next.js frontend hosting, Edge Middleware, and DNS routing.",
    category: "Cloud Infrastructure & Hosting",
    website: "https://vercel.com",
    dataProcessed: ["Client Request IPs", "Transient HTTP Headers"],
    dataLocation: "Global Edge Network",
    dpaUrl: "https://vercel.com/legal/dpa",
    dpaStatus: "Signed",
    certifications: ["SOC 2 Type II", "ISO 27001", "GDPR Compliant"],
    riskLevel: "Low",
    lastReviewedDate: "2026-06-10",
    nextReviewDate: "2027-06-10",
    notes: "Signed Enterprise Terms & DPA on file.",
    isPublic: true,
    addedAt: "2026-01-11T09:15:00Z",
  },
  {
    id: "v-5",
    name: "Resend",
    slug: "resend",
    description: "Transactional notifications, welcome emails, and password resets.",
    category: "Customer Support & Communication",
    website: "https://resend.com",
    dataProcessed: ["Recipient Email", "Notification Body Content"],
    dataLocation: "United States (US-East)",
    dpaUrl: "https://resend.com/legal/dpa",
    dpaStatus: "Under Review",
    certifications: ["SOC 2 Type II", "GDPR Compliant"],
    riskLevel: "Medium",
    lastReviewedDate: "2026-07-01",
    nextReviewDate: "2026-09-01",
    notes: "Annual vendor reassessment due before upcoming audit.",
    isPublic: true,
    addedAt: "2026-02-01T11:00:00Z",
  },
  {
    id: "v-6",
    name: "PostHog",
    slug: "posthog",
    description: "Product telemetry, feature flags, and anonymous conversion funnels.",
    category: "Analytics & Observability",
    website: "https://posthog.com",
    dataProcessed: ["User Action Events", "Browser Device Type", "Pseudonymous IDs"],
    dataLocation: "United States (US-East)",
    dpaUrl: "https://posthog.com/terms#data-processing-agreement",
    dpaStatus: "Signed",
    certifications: ["SOC 2 Type II", "GDPR Compliant"],
    riskLevel: "Low",
    lastReviewedDate: "2026-05-20",
    nextReviewDate: "2027-05-20",
    notes: "EU/US DPA signed. IP masking enabled by default.",
    isPublic: true,
    addedAt: "2026-02-10T14:30:00Z",
  },
  {
    id: "v-7",
    name: "Sentry",
    slug: "sentry",
    description: "Real-time error monitoring and exception tracking.",
    category: "Analytics & Observability",
    website: "https://sentry.io",
    dataProcessed: ["Client Stack Traces", "Browser Metadata"],
    dataLocation: "United States",
    dpaUrl: "https://sentry.io/legal/dpa/",
    dpaStatus: "Signed",
    certifications: ["SOC 2 Type II", "HIPAA", "GDPR Compliant"],
    riskLevel: "Low",
    lastReviewedDate: "2026-03-15",
    nextReviewDate: "2027-03-15",
    notes: "Data scrubbing configured to remove PII from error payloads.",
    isPublic: true,
    addedAt: "2026-02-15T16:00:00Z",
  },
  {
    id: "v-8",
    name: "Pinecone",
    slug: "pinecone",
    description: "Managed vector database storing semantic document embeddings.",
    category: "Database & Storage",
    website: "https://pinecone.io",
    dataProcessed: ["Document Vector Embeddings", "Document IDs"],
    dataLocation: "United States (US-East-1)",
    dpaUrl: "https://www.pinecone.io/legal/dpa/",
    dpaStatus: "Missing",
    certifications: ["SOC 2 Type II", "GDPR Compliant"],
    riskLevel: "High",
    lastReviewedDate: "2026-01-20",
    nextReviewDate: "2026-08-30",
    notes: "Action item: Execute formal DPA with Pinecone legal team.",
    isPublic: false,
    addedAt: "2026-03-01T10:00:00Z",
  }
];
