/**
 * bridge-tendon-acoustic-emission-localizer.ts
 * SNAP-62: Prestressed Concrete Bridge Tendon Acoustic Emission Wire-Break Localizer.
 * Part of SnapInspect AI Tactical Field Inspection CAD & Mobile Voice AI.
 *
 * Implements NDT Acoustic Emission (AE) continuous monitoring for prestressed and post-tensioned bridge girders:
 * 1. Discriminates high-energy transient elastic stress waves (50-400 kHz) generated by high-strength steel wire rupture.
 * 2. Uses 1D Time Difference of Arrival (TDoA) along linear waveguide sensor arrays.
 * 3. Filters out ambient traffic vibrations and grout micro-fretting via rise-time and MARSE energy thresholds.
 * 4. Models cumulative cross-sectional prestress loss and generates critical bridge safety alerts.
 */

export interface AeSensorHit {
  sensorId: string;
  sensorPositionMeters: number;
  arrivalTimestampSeconds: number; // Sub-microsecond precision timestamp
  peakAmplitudeDb: number;        // e.g. 40 to 95 dB
  riseTimeMicroseconds: number;   // e.g. 5 to 150 us
  energyMarseCounts: number;      // Measured Area under Rectified Signal Envelope
  durationMicroseconds: number;
}

export interface TendonWireBreakEvent {
  eventId: string;
  tendonDuctId: string;
  estimatedLocationMeters: number;
  hitCount: number;
  isConfirmedWireBreak: boolean;
  classificationReason: string;
  stressWaveSpeedMetersPerSec: number;
}

export interface TendonHealthAssessment {
  tendonDuctId: string;
  totalStrands: number;
  wiresPerStrand: number;
  totalInitialWires: number;
  confirmedBreaksCount: number;
  prestressLossPercentage: number;
  safetyStatus: 'NORMAL' | 'ELEVATED_WATCH' | 'CRITICAL_INSPECTION_REQUIRED';
  events: TendonWireBreakEvent[];
  recommendations: string[];
}

export class BridgeTendonAcousticEmissionLocalizer {
  // Waveguide acoustic velocity in 7-wire low-relaxation prestressing steel strand (~5050 m/s)
  public static readonly DEFAULT_STEEL_WAVE_VELOCITY_MPS = 5050.0;

  // Typical wire-break diagnostic discrimination criteria:
  // True wire breaks exhibit sharp rise times (< 25 us) and high peak amplitudes (> 70 dB)
  public static readonly MIN_WIRE_BREAK_AMPLITUDE_DB = 70.0;
  public static readonly MAX_WIRE_BREAK_RISE_TIME_US = 30.0;
  public static readonly MIN_WIRE_BREAK_ENERGY_COUNTS = 400;

  /**
   * Localizes a single acoustic event along a linear tendon sensor array using TDoA.
   */
  public static localizeEvent(
    tendonDuctId: string,
    hits: AeSensorHit[],
    waveVelocityMps: number = BridgeTendonAcousticEmissionLocalizer.DEFAULT_STEEL_WAVE_VELOCITY_MPS
  ): TendonWireBreakEvent {
    if (hits.length < 2) {
      throw new Error('At least 2 sensor hits are required for 1D linear TDoA localization.');
    }

    // Sort hits by arrival time
    const sortedHits = [...hits].sort((a, b) => a.arrivalTimestampSeconds - b.arrivalTimestampSeconds);
    const hit1 = sortedHits[0];
    const hit2 = sortedHits[1];

    const deltaT = hit2.arrivalTimestampSeconds - hit1.arrivalTimestampSeconds;
    const x1 = hit1.sensorPositionMeters;
    const x2 = hit2.sensorPositionMeters;

    // Linear TDoA equation:
    // deltaT = (d2 - d1) / v = (|x - x2| - |x - x1|) / v
    // Assuming event occurs between sensor 1 and sensor 2 (or along the span):
    let estimatedLocation: number;
    if (x2 > x1) {
      estimatedLocation = (x1 + x2 - waveVelocityMps * deltaT) / 2.0;
    } else {
      estimatedLocation = (x1 + x2 + waveVelocityMps * deltaT) / 2.0;
    }

    // Clamp to sensor span bounds
    const minX = Math.min(x1, x2);
    const maxX = Math.max(x1, x2);
    const clampedLocation = Number(Math.max(minX, Math.min(maxX, estimatedLocation)).toFixed(3));

    // Acoustic signature classification
    const maxAmp = Math.max(...hits.map(h => h.peakAmplitudeDb));
    const minRiseTime = Math.min(...hits.map(h => h.riseTimeMicroseconds));
    const totalEnergy = hits.reduce((sum, h) => sum + h.energyMarseCounts, 0);

    const isConfirmedWireBreak =
      maxAmp >= BridgeTendonAcousticEmissionLocalizer.MIN_WIRE_BREAK_AMPLITUDE_DB &&
      minRiseTime <= BridgeTendonAcousticEmissionLocalizer.MAX_WIRE_BREAK_RISE_TIME_US &&
      totalEnergy >= BridgeTendonAcousticEmissionLocalizer.MIN_WIRE_BREAK_ENERGY_COUNTS;

    let reason = 'Confirmed rapid high-energy brittle wire snap transient.';
    if (!isConfirmedWireBreak) {
      if (maxAmp < BridgeTendonAcousticEmissionLocalizer.MIN_WIRE_BREAK_AMPLITUDE_DB) {
        reason = `Sub-threshold amplitude (${maxAmp.toFixed(1)} dB < 70 dB); likely grout micro-cracking or ambient traffic.`;
      } else if (minRiseTime > BridgeTendonAcousticEmissionLocalizer.MAX_WIRE_BREAK_RISE_TIME_US) {
        reason = `Slow waveform rise time (${minRiseTime.toFixed(1)} us); classified as frictional fretting rather than snap.`;
      } else {
        reason = 'Low acoustic MARSE energy counts; non-rupture disturbance.';
      }
    }

    return {
      eventId: `AE-EVT-${tendonDuctId}-${Math.round(clampedLocation * 100)}`,
      tendonDuctId,
      estimatedLocationMeters: clampedLocation,
      hitCount: hits.length,
      isConfirmedWireBreak,
      classificationReason: reason,
      stressWaveSpeedMetersPerSec: waveVelocityMps,
    };
  }

  /**
   * Assesses overall tendon health given cumulative events over time.
   */
  public static evaluateTendonHealth(
    tendonDuctId: string,
    totalStrands: number,
    wiresPerStrand: number = 7,
    events: TendonWireBreakEvent[]
  ): TendonHealthAssessment {
    const totalInitialWires = totalStrands * wiresPerStrand;
    const confirmedBreaks = events.filter(e => e.isConfirmedWireBreak).length;
    const prestressLossPct = Number(((confirmedBreaks / totalInitialWires) * 100.0).toFixed(2));

    let status: TendonHealthAssessment['safetyStatus'] = 'NORMAL';
    const recommendations: string[] = [];

    if (prestressLossPct >= 5.0 || confirmedBreaks >= 10) {
      status = 'CRITICAL_INSPECTION_REQUIRED';
      recommendations.push('Immediate structural load restriction recommended.');
      recommendations.push('Conduct ultrasonic shear-wave tomography and intrusive borescope inspection of duct grout.');
    } else if (prestressLossPct >= 1.5 || confirmedBreaks >= 3) {
      status = 'ELEVATED_WATCH';
      recommendations.push('Increase AE monitoring sample frequency and monitor wire-break cluster concentration.');
    } else {
      status = 'NORMAL';
      recommendations.push('Tendon structural capacity within design safety margins.');
    }

    return {
      tendonDuctId,
      totalStrands,
      wiresPerStrand,
      totalInitialWires,
      confirmedBreaksCount: confirmedBreaks,
      prestressLossPercentage: prestressLossPct,
      safetyStatus: status,
      events,
      recommendations,
    };
  }
}
